### PR TITLE
feat: add an option to support custom 404 pages

### PR DESCRIPTION
**Pull request by gilbsgilbs**
Thanks for sharing this useful caddy module. I made this tiny feature that allows fallback to another key from the bucket in case the target object doesn't exist. I used to do this with very exotic nginx conf for static website hosting :yum: . Let me know what you think.

### CODE REVIEW

**Comment by gilbsgilbs** [comment]
(I don't think the CI fail is due to my PR :zipper_mouth_face: . golangci-lint seems utterly slow at the moment.)

**Review by rayjlinden — COMMENTED** [review]
So sorry for the delay in getting back to you on this.  I just merged the PR you had for ETag.  It was easy to understand what you did.  I still need to wrap my head around this one.  I love the idea - though!  I'll look at it again in the morning - it is a little late for me now.

One thing I currently do not understand is the example/Dockerfile.  How does this improve the workflow?  The `make docker` does the same thing but builds the local version.  Where it seems the Dockerfile would build only the published version.  That would be painful for local development.  However, I have a feeling I'm missing something.  There must be a way to override that or something?

**Comment by gilbsgilbs** [comment]
> One thing I currently do not understand is the example/Dockerfile. How does this improve the workflow? The make docker does the same thing but builds the local version. Where it seems the Dockerfile would build only the published version. That would be painful for local development. However, I have a feeling I'm missing something. There must be a way to override that or something?

I think you didn't miss anything and I missed the Makefile and Dockerfile at the project root :facepalm: . It wasn't clear to me how to use the examples with a local build, so I came up with my own way. Turns out the way you intended this to work is just more natural. Let me just revert my mess, sorry.

**Comment by gilbsgilbs** [comment]
Though I wonder if we'd wouldn't also want to support custom pages for other HTTP statuses, such as 403. I'm just unsure how "mapping of values" are usually handled in Caddyfiles. Would something like this even work:

```
s3_proxy {
  ...
  error_page 404 "_404.html"
  error_page 403 "_403.html"
}
```

**Comment by gilbsgilbs** [comment]
Let's close this in favor of #11. I added support for any error page, not only 404.

**Pull request closed without merging**
